

/***************************************************************************************************

Sets up a simple address table with a geometry column. The table is used in the GIS section of the course.

The examples use the database dlh_adv_sql, which is created by the setup.sql script.

2026 Copyright: Marc Linster
Last updated Oct 6, 2026

****************************************************************************************************/





DROP TABLE IF EXISTS address;

CREATE TABLE address (
   	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	rue text COLLATE pg_catalog."default",
    numero text COLLATE pg_catalog."default",
    localite text COLLATE pg_catalog."default",
    code_postal text COLLATE pg_catalog."default",
    lat_wgs84 double precision,
    lon_wgs84 double precision,
    commune text COLLATE pg_catalog."default",
    geom geometry(Point,4326) GENERATED ALWAYS AS (st_setsrid(st_makepoint(lon_wgs84, lat_wgs84), 4326)) STORED
);

CREATE INDEX address_geom_idx ON address USING GIST (geom);
