DROP TABLE IF EXISTS address;

CREATE TABLE address (
   	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	rue text COLLATE pg_catalog."default",
    numero text COLLATE pg_catalog."default",
    localite text COLLATE pg_catalog."default",
    code_postal text COLLATE pg_catalog."default",
    lat_wgs84 double precision,
    lon_wgs84 double precision,
    commune text COLLATE pg_catalog."default",
    geom geometry(Point,4326) GENERATED ALWAYS AS (st_setsrid(st_makepoint(lon_wgs84, lat_wgs84), 4326)) STORED
);

CREATE INDEX address_geom_idx ON address USING GIST (geom);
