DROP TABLE IF EXISTS category;

CREATE TABLE category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
    description TEXT
);

INSERT INTO category (id, name, description) VALUES
    (14, 'Electronics', 'Electronic devices and accessories'),
    (10, 'Clothing', 'Apparel and fashion items'),
    (11, 'Home & Kitchen', 'Household and kitchen essentials'),
    (12, 'Books', 'Printed and digital reading material'),
    (13, 'Sports & Outdoors', 'Outdoor gear and active lifestyle products'),
    (9, 'Health & Personal Care', 'Wellness and personal care products'),
    (15, 'Toys & Games', 'fun items for children and families'),
    (16, 'Automotive', 'vehicle parts and accessories'),
    (17, 'Beauty', 'Cosmetics and personal grooming items'),
    (5, 'Grocery', 'Everyday food and household staples'),
    (6, 'Food', 'Prepared and packaged food items'),
    (7, 'Drink', 'Beverages and refreshments'),
    (8, 'Snack', 'Light bites and quick snacks');

-- makes sure that new insert statements work correctly
SELECT setval('category_id_seq', 21, true);