DROP TABLE IF EXISTS category;

CREATE TABLE category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

INSERT INTO category (id, name) VALUES
    (14,'Electronics'),
    (10, 'Clothing'),
    (11, 'Home & Kitchen'),
    (12, 'Books'),
    (13, 'Sports & Outdoors'),
    (9, 'Health & Personal Care'),
    (15, 'Toys & Games'),
    (16, 'Automotive'),
    (17, 'Beauty'),
    (5, 'Grocery'),
    (6, 'Food'),
    (7, 'Drink'),
    (8, 'Snack');

SELECT setval('category_id_seq', 21, true);