DROP TABLE IF EXISTS customer CASCADE;

CREATE TABLE customer  (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    address_id INTEGER REFERENCES address(id),
    since DATE,
    phone_numbers JSONB,
    email_addresses JSONB,
    social_media JSONB
);    

TRUNCATE customer CASCADE;
CREATE OR REPLACE PROCEDURE insert_random_customers(num_customers INT)
LANGUAGE plpgsql
AS $$
DECLARE
    i INT;
    first_names TEXT[] := ARRAY['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia', 
                        'Kevin', 'Laura', 'Mike', 'Nina', 'Oliver', 'Paula', 'Quinn', 'Rachel', 'Sam', 'Tina', 'Marc', 
                        'Sophie', 'Luke', 'Nina', 'Max', 'Emma', 'Lena', 'Tom', 'Mia', 'Marc', 'Claire', 'Julien', 'Laura', 'Pierre', 
                        'Sarah', 'Lucas', 'Emma', 'Leo', 'Nina', 'Alex', 'Sophie', 'Tom', 'Lena', 'Paul', 'Pia'];
    last_names TEXT[] := ARRAY['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia', 'Rodriguez', 
                        'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson',
                        'Martin', 'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 
                        'Robinson', 'Walker', 'Young', 'Allen', 'King', 'Wright', 'Scott', 'Mueller', 'Hill', 'Adams', 
                        'Baker', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Bintner', 'Ewen', 'Linster', 'Thull', 'Lagrange',
                        'Becker', 'Wagner', 'Keller', 'Fischer', 'Schmit', 'Stein', 'Hoffmann', 'Schneider', 'Lang', 'Frank', 'Weber', 'Muller', 'Klein'];
    random_first_name TEXT;
    random_last_name TEXT;
BEGIN
    FOR i IN 1..num_customers LOOP
        random_first_name := first_names[1 + floor(random() * array_length(first_names, 1))];
        random_last_name := last_names[1 + floor(random() * array_length(last_names, 1))];
        INSERT INTO customer (id, first_name, last_name, address_id, since, phone_numbers, email_addresses, social_media)
        VALUES (i, random_first_name, random_last_name, NULL, CURRENT_DATE - (random() * 2* 365)::INT, NULL, 
                jsonb_build_array(jsonb_build_object('email', random_first_name || '.' || random_last_name || '@example.com')), NULL);
    END LOOP;
END;
$$;

CALL insert_random_customers(5000);

SELECT setval('customer_id_seq', 5001, true);

-- assign random addresses to customers
CREATE OR REPLACE PROCEDURE assign_random_addresses_to_customers()
LANGUAGE plpgsql
AS $$
DECLARE
    v_customer_id INT;
    v_address_id INT;
BEGIN
    FOR v_customer_id IN SELECT id FROM customer LOOP
        SELECT id INTO v_address_id FROM address ORDER BY random() LIMIT 1;
        UPDATE customer SET address_id = v_address_id WHERE id = v_customer_id;
    END LOOP;
END;
$$;

CALL assign_random_addresses_to_customers();

/* assign random phone numbers to customers using the following format:

    {
        "work": {
            "mobile": "(+352) 123 456 789", 
            "car": "(+352) 987 654 321",
            "office": ["(+352) 234 567 890"
        },
        "private": {
            "home": "(+352) 345 678 901", 
            "mobile": "(+352) 456 789 012",
            "weekend house": ["(+352) 567 890 123"]
        }
    }
*/

CREATE OR REPLACE PROCEDURE assign_random_phone_numbers_to_customers()
LANGUAGE plpgsql
AS $$
DECLARE
    v_customer_id INT;
    v_phone_number TEXT;
    v_phone_group TEXT;
    v_phone_label TEXT;
    v_phone_json_work JSONB;
    v_phone_json_private JSONB;
    v_phone_json JSONB;
    
BEGIN
    UPDATE customer SET phone_numbers = NULL;
    FOR v_customer_id IN SELECT id FROM customer LOOP
    -- work numbers
    v_phone_group = 'work';
    --  random phone number
    v_phone_number := '(+352) ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100) :: INT;
    v_phone_label := CASE WHEN random() < 0.33 THEN 'mobile' WHEN random() < 0.66 THEN 'car' ELSE 'office' END;
    v_phone_json := jsonb_build_object(v_phone_label, v_phone_number);
    -- Assign 30% of the customers a second, different phone number with a different label
    IF random() < 0.3 THEN
        v_phone_number := '(+352) ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100) :: INT;    
        v_phone_label := CASE WHEN random() < 0.33 THEN 'mobile' WHEN random() < 0.66 THEN 'car' ELSE 'office' END;
        v_phone_json := v_phone_json || jsonb_build_object(v_phone_label, v_phone_number);
    END IF;
    v_phone_json_work := jsonb_build_object(v_phone_group, v_phone_json);
    -- private numbers
    v_phone_group = 'private';
    v_phone_number := '(+352) ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100    )::INT || ' ' || (floor(random() * 900) + 100) :: INT;
    v_phone_label := CASE WHEN random() < 0.33 THEN 'home' WHEN random() < 0.66 THEN 'mobile' ELSE 'weekend house' END;
    v_phone_json := jsonb_build_object(v_phone_label, v_phone_number);
    -- Assign 30% of the customers a second, different phone number with a different label
    IF random() < 0.3 THEN
        v_phone_number := '(+352) ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100)::INT || ' ' || (floor(random() * 900) + 100) :: INT;
        v_phone_label := CASE WHEN random() < 0.33 THEN 'home' WHEN random() < 0.66 THEN 'mobile' ELSE 'weekend house' END;
        v_phone_json := v_phone_json || jsonb_build_object(v_phone_label, v_phone_number);
    END IF;
    v_phone_json_private := jsonb_build_object(v_phone_group, v_phone_json);
    v_phone_json := v_phone_json_work || v_phone_json_private;
        -- Update customer with phone number
        UPDATE customer 
        SET phone_numbers = v_phone_json
        WHERE id = v_customer_id;
    END LOOP;
END;
$$; 

CALL assign_random_phone_numbers_to_customers();

-- assign random email addresses to customers, with the domain being one of "example.com", "test.com", "demo.com"
-- 30% of the customers should have a second email address with a different domain
CREATE OR REPLACE PROCEDURE assign_random_email_addresses_to_customers()
LANGUAGE plpgsql
AS $$
DECLARE
    customer_id INT;
    v_first_name TEXT;
    v_last_name TEXT;
    email_domain TEXT;
    email_json JSONB;
BEGIN
    FOR customer_id IN SELECT id FROM customer LOOP
        SELECT first_name, last_name INTO v_first_name, v_last_name FROM customer WHERE id = customer_id;
        email_domain := CASE WHEN random() < 0.33 THEN 'example.com' WHEN random() < 0.66 THEN 'test.com' ELSE 'demo.com' END;
        email_json := jsonb_build_object('email', v_first_name || '.' || v_last_name || customer_id || '@' || email_domain);
        -- Assign 30% of the customers a second email address with a different domain
        IF random() < 0.3 THEN
            email_domain := CASE WHEN random() < 0.33 THEN 'google.com' WHEN random() < 0.66 THEN 'pt.com' ELSE 'microsoft.com' END;
            email_json := email_json || jsonb_build_object('work_email', v_last_name || '.' || v_first_name || '@' || email_domain);
        END IF;
        UPDATE customer 
        SET email_addresses = email_json
        WHERE id = customer_id;
    END LOOP;
END;
$$;

call assign_random_email_addresses_to_customers();