DROP TABLE IF EXISTS customer CASCADE;

CREATE TABLE customer  (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    address_id INTEGER REFERENCES address(id),
    since DATE,
    phone_numbers JSONB,
    email_addresses JSONB,
    social_media JSONB
);    

TRUNCATE customer CASCADE;
CREATE OR REPLACE PROCEDURE insert_random_customers(num_customers INT)
LANGUAGE plpgsql
AS $$
DECLARE
    i INT;
    first_names TEXT[] := ARRAY['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ian', 'Julia', 
                        'Kevin', 'Laura', 'Mike', 'Nina', 'Oliver', 'Paula', 'Quinn', 'Rachel', 'Sam', 'Tina', 'Marc', 
                        'Sophie', 'Luke', 'Nina', 'Max', 'Emma', 'Lena', 'Tom', 'Mia', 'Marc', 'Claire', 'Julien', 'Laura', 'Pierre', 
                        'Sarah', 'Lucas', 'Emma', 'Leo', 'Nina', 'Alex', 'Sophie', 'Tom', 'Lena', 'Paul', 'Pia'];
    last_names TEXT[] := ARRAY['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Garcia', 'Rodriguez', 
                        'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson',
                        'Martin', 'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 
                        'Robinson', 'Walker', 'Young', 'Allen', 'King', 'Wright', 'Scott', 'Mueller', 'Hill', 'Adams', 
                        'Baker', 'Nelson', 'Carter', 'Mitchell', 'Perez', 'Roberts', 'Turner', 'Bintner', 'Ewen', 'Linster', 'Thull', 'Lagrange',
                        'Becker', 'Wagner', 'Keller', 'Fischer', 'Schmit', 'Stein', 'Hoffmann', 'Schneider', 'Lang', 'Frank', 'Weber', 'Muller', 'Klein'];
    random_first_name TEXT;
    random_last_name TEXT;
BEGIN
    FOR i IN 1..num_customers LOOP
        random_first_name := first_names[1 + floor(random() * array_length(first_names, 1))];
        random_last_name := last_names[1 + floor(random() * array_length(last_names, 1))];
        INSERT INTO customer (id, first_name, last_name, address_id, since, phone_numbers, email_addresses, social_media)
        VALUES (i, random_first_name, random_last_name, NULL, CURRENT_DATE - (random() * 365)::INT, NULL, 
                jsonb_build_array(jsonb_build_object('email', random_first_name || '.' || random_last_name || '@example.com')), NULL);
    END LOOP;
END;
$$;

CALL insert_random_customers(5000);

SELECT setval('customer_id_seq', 5001, true);

-- assign random addresses to customers
CREATE OR REPLACE PROCEDURE assign_random_addresses_to_customers()
LANGUAGE plpgsql
AS $$
DECLARE
    v_customer_id INT;
    v_address_id INT;
BEGIN
    FOR v_customer_id IN SELECT id FROM customer LOOP
        SELECT id INTO v_address_id FROM address ORDER BY random() LIMIT 1;
        UPDATE customer SET address_id = v_address_id WHERE id = v_customer_id;
    END LOOP;
END;
$$;

CALL assign_random_addresses_to_customers();