DROP TABLE IF EXISTS purchase CASCADE;

CREATE TABLE purchase (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE,
    customer_id INTEGER REFERENCES customer(id),
    product_nbr TEXT REFERENCES product(product_nbr),
    quantity INTEGER CHECK (quantity > 0)
);

-- stored procedure to create purchase data for random customers and products over the last 2 years
CREATE OR REPLACE PROCEDURE generate_purchase_data(num_purchases INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
    i INTEGER;
    v_customer_count INTEGER;
    random_customer_id INTEGER;
    random_product_nbr TEXT;
    random_quantity INTEGER;
    random_date DATE;
BEGIN
    -- this assumes that the customer and product tables are already populated with data and that IDs are sequential and start from 1
    SELECT COUNT(*) INTO v_customer_count FROM customer;
    v_customer_count = v_customer_count * 0.8; -- Use 80% of customers to have customers with purchases, the rest will have no purchases
    FOR i IN 1..num_purchases LOOP
        -- Select a random customer ID
        random_customer_id = FLOOR(RANDOM() * v_customer_count + 1);
        -- Select a random product ID, but exclude butter
        SELECT product_nbr INTO random_product_nbr FROM product WHERE product_nbr <> 'butter' ORDER BY RANDOM() LIMIT 1;
        -- Generate a random quantity
        SELECT FLOOR(RANDOM() * 10 + 1) INTO random_quantity;
        -- Generate a random date within the last 2 years
        SELECT CURRENT_DATE - FLOOR(RANDOM() * 730 + 1)::INT INTO random_date;
        -- Insert the purchase data
        INSERT INTO purchase (date, customer_id, product_nbr, quantity)
        VALUES (random_date, random_customer_id, random_product_nbr, random_quantity);
    END LOOP;
END;
$$;

CALL generate_purchase_data(100000); -- Generate 100000 random purchase records
