

/*

Data Triggers


*/

-- a simple trigger to demonstrate the concept and illustrate the trigger-specific variables

CREATE OR REPLACE FUNCTION tr_product_change () RETURNS TRIGGER 
AS 
$$
    BEGIN
    RAISE NOTICE 'Price changed from % to % for product % ', OLD.price, NEW.price, OLD.product_nbr;
    RAISE NOTICE 'Old record %', OLD;
    RAISE NOTICE 'New record %', NEW;
    RAISE NOTICE 'Trigger name % called when % at level % for operation %',
        TG_NAME, TG_WHEN, TG_LEVEL, TG_OP;
    RETURN NEW;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_change_notice
    BEFORE INSERT OR UPDATE 
    ON product
FOR EACH ROW EXECUTE FUNCTION tr_product_change();

-- try it out

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('new_cheese', 5, 'Cheese 10% fat', 19.00);

UPDATE product SET price = 20.00 WHERE product_nbr = 'new_cheese';        

DELETE FROM product WHERE product_nbr = 'new_cheese';

-- create a trigger that fires on DELETE

CREATE OR REPLACE FUNCTION tr_product_delete_notice () RETURNS TRIGGER
AS
$$
    BEGIN
    RAISE NOTICE 'Deleting product % with the following info %',
        OLD.product_nbr, OLD;
    RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_delete 
    BEFORE DELETE
    ON product
FOR EACH ROW EXECUTE FUNCTION tr_product_delete_notice ();

DELETE FROM product WHERE product_nbr = 'new_cheese';

-- add a trigger that rounds prices on UPDATE

-- modify the original trigger to only fire on INSERT

CREATE OR REPLACE TRIGGER tr_product_change_notice
    BEFORE INSERT OF price
    ON product
FOR EACH ROW EXECUTE FUNCTION tr_product_change();

-- define a function that rounds the price and writes a message
CREATE OR REPLACE FUNCTION tr_product_price_round () RETURNS TRIGGER 
AS 
$$
    DECLARE v_original_price NUMERIC(10,2);
    BEGIN
        v_original_price = NEW.price;
        NEW.price = ROUND (v_original_price);
        RAISE NOTICE 'Price changed from % to % for product % after rounding from %', 
            OLD.price, NEW.price, OLD.product_nbr, v_original_price;
    RETURN NEW;
    END;
$$ LANGUAGE PLPGSQL;

-- add it as a trigger that fires on update of the price 
CREATE OR REPLACE TRIGGER tr_product_update_notice
    BEFORE UPDATE OF price
    ON product
FOR EACH ROW EXECUTE FUNCTION tr_product_price_round();

-- try it out

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('new_cheese', 5, 'Cheese 10% fat', 19.00);

UPDATE product SET price = 20.99 WHERE product_nbr = 'new_cheese';    

UPDATE product SET name = 'modified the name' WHERE product_nbr = 'new_cheese';

-- create a log table for price changes

DROP TABLE product_price_history;

CREATE TABLE product_price_history
    (id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    product_nbr TEXT REFERENCES product (product_nbr),
    update_time timestamp NOT NULL,
    old_price NUMERIC (10,2),
    new_price NUMERIC (10,2));


CREATE OR REPLACE FUNCTION tr_product_price_change () RETURNS TRIGGER
AS 
$$ 
    BEGIN
        INSERT INTO product_price_history
            (product_nbr, update_time, old_price, new_price)
        VALUES
            (NEW.product_nbr, NOW(), OLD.price, NEW.price);
        RAISE NOTICE 'Product price change logged'
        RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_price_update
    AFTER UPDATE OF price
    ON product
FOR EACH ROW EXECUTE FUNCTION tr_product_price_change();

UPDATE product SET price = 21.99 WHERE product_nbr = 'new_cheese';    

UPDATE product SET name = 'Super cheese' WHERE product_nbr = 'new_cheese';   

SELECT * FROM product_price_history;