

/*

Data Triggers


*/

-- a simple trigger to demonstrate the concept and illustrate the trigger-specific variables

CREATE OR REPLACE FUNCTION trf_product_change () RETURNS TRIGGER 
AS 
$$
    BEGIN
    RAISE NOTICE 'Trigger name % called % at level % for operation %',
        TG_NAME, TG_WHEN, TG_LEVEL, TG_OP;
    RAISE NOTICE 'Price changed from % to % for product % ', OLD.price, NEW.price, OLD.product_nbr;
    RAISE NOTICE 'Old record %', OLD;
    RAISE NOTICE 'New record %', NEW;

    RETURN NEW;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_change
    BEFORE INSERT OR UPDATE 
    ON product
FOR EACH ROW EXECUTE FUNCTION trf_product_change();

-- try it out

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('new_cheese', 5, 'Cheese 10% fat', 19.00);

UPDATE product SET price = 20.00 WHERE product_nbr = 'new_cheese';        

DELETE FROM product WHERE product_nbr = 'new_cheese';

-- create a trigger that fires on DELETE

CREATE OR REPLACE FUNCTION trf_product_delete () RETURNS TRIGGER
AS
$$
    BEGIN
    RAISE NOTICE 'Deleting product % with the following info %',
        OLD.product_nbr, OLD;
    -- OLD needs to be returned, as NEW is not defined in delete
    RETURN OLD;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_delete 
    BEFORE DELETE
    ON product
FOR EACH ROW EXECUTE FUNCTION trf_product_delete ();

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('new_cheese', 5, 'Cheese 10% fat', 19.00);

DELETE FROM product WHERE product_nbr = 'new_cheese';

-- add a trigger that rounds prices on UPDATE

-- modify the original trigger to only fire on INSERT, as we create a new one for UPDATE

CREATE OR REPLACE TRIGGER tr_product_change
    BEFORE INSERT
    ON product
FOR EACH ROW EXECUTE FUNCTION trf_product_change();

-- define a function that rounds the price and writes a message
CREATE OR REPLACE FUNCTION trf_product_price_round () RETURNS TRIGGER 
AS 
$$
    DECLARE v_original_price NUMERIC(10,2);
    BEGIN
        v_original_price = NEW.price;
        NEW.price = ROUND (v_original_price);
        RAISE NOTICE 'Price changed from % to % for product % after rounding from %', 
            OLD.price, NEW.price, NEW.product_nbr, v_original_price;
    RETURN NEW;
    END;
$$ LANGUAGE PLPGSQL;

-- add it as a trigger that fires on update of the price 
CREATE OR REPLACE TRIGGER tr_product_price_round
    BEFORE UPDATE OF price
    ON product
FOR EACH ROW EXECUTE FUNCTION trf_product_price_round();

-- try it out

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('new_cheese', 5, 'Cheese 10% fat', 19.00);

UPDATE product SET price = 20.99 WHERE product_nbr = 'new_cheese';    

UPDATE product SET name = 'modified the name' WHERE product_nbr = 'new_cheese';

-- create a log table for price changes

DROP TABLE IF EXISTS product_price_history;

CREATE TABLE product_price_history
    (id integer PRIMARY KEY  GENERATED BY DEFAULT AS IDENTITY,
    product_nbr TEXT REFERENCES product (product_nbr),
    update_time timestamp NOT NULL,
    old_price NUMERIC (10,2),
    new_price NUMERIC (10,2));


CREATE OR REPLACE FUNCTION trf_product_price_change_log () RETURNS TRIGGER
AS 
$$ 
    BEGIN
        INSERT INTO product_price_history
            (product_nbr, update_time, old_price, new_price)
        VALUES
            (NEW.product_nbr, NOW(), OLD.price, NEW.price);
        RAISE NOTICE 'Product price change logged';
        RETURN NULL;
    END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_price_update
    AFTER UPDATE OF price
    ON product
FOR EACH ROW EXECUTE FUNCTION trf_product_price_change_log();

UPDATE product SET price = 21.99 WHERE product_nbr = 'new_cheese';    

UPDATE product SET name = 'Super cheese' WHERE product_nbr = 'new_cheese';   

SELECT * FROM product_price_history;

-- Example of a statement-level trigger.
-- This counts the rows before or after an insert or delete
CREATE OR REPLACE FUNCTION trf_product_count () RETURNS TRIGGER
AS
$$
DECLARE 
    v_row_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_row_count FROM product;
    RAISE NOTICE 'Statement trigger % fired for % on table %',
        TG_NAME, TG_OP, TG_TABLE_NAME;
    IF TG_WHEN = 'BEFORE' THEN
        RAISE NOTICE 'Before executing, the table had % rows', v_row_count;
    ELSE 
        RAISE NOTICE 'After executing, the table had % rows', v_row_count;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_product_count_before
    BEFORE UPDATE OR INSERT OR DELETE OR TRUNCATE
    ON product
FOR EACH STATEMENT EXECUTE FUNCTION trf_product_count();


CREATE OR REPLACE TRIGGER tr_product_count_after
    AFTER UPDATE OR INSERT OR DELETE OR TRUNCATE
    ON product
FOR EACH STATEMENT EXECUTE FUNCTION trf_product_count();

-- Fires once for the UPDATE statement, even if it matches multiple rows.
UPDATE product SET name = name WHERE product_nbr = 'new_cheese';

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('sausage2', 5, 'Grouss Zosiss', 19.00),
        ('sausage1', 5, 'Kleng Zosiss', 5.00)

-- Drop all the row-level triggers

DROP TRIGGER tr_product_change ON product;
DROP TRIGGER tr_product_delete ON product;
DROP TRIGGER tr_product_price_round ON product;
DROP TRIGGER tr_product_price_update ON product;

INSERT INTO product (product_nbr, category_id, name, price) 
    VALUES 
        ('sausage3', 5, 'Mettwurscht', 19.00),
        ('sausage4', 5, 'Grillwurst', 5.00);